# Generated by Django 4.0.2 on 2022-04-06 16:42

import django.db.models.deletion
from django.db import migrations, models

import gesasso.api.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[("RSA", "RSA")], default="RSA", max_length=30
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        choices=[("MK_MAIL", "MK_MAIL")],
                        default="MK_MAIL",
                        max_length=10,
                    ),
                ),
                ("public_key", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MailRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("mail_from", models.EmailField(max_length=254)),
                ("mail_to", models.EmailField(max_length=254)),
                ("mail_subject", models.CharField(max_length=150)),
                ("mail_body", models.TextField()),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.request",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
        migrations.RunSQL(
            "INSERT INTO `listener_cryptokey` (`created`, `updated`, `removed`, `name`, `type`, `agent`, `public_key`)"
            " VALUES (now(), now(), NULL, 'MK_Mail Dev', 'RSA', 'MK_MAIL', "
            "'-----BEGIN PUBLIC KEY-----\r\n"
            "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCFg8EPxiCWVPNcTxL982rhdZRp\r\n"
            "W77GyaRT3NEAOFA9CsUEq/1rsTIMJAqdZmAVAdqwzrpFeFEaNcHZlJfT8xepOkhr\r\n"
            "4l8imgrjV9Rwhb8xT4yycmQxg7QAUXNk4XKijKzcOplmNt2xFKqzDVjpCx9WURPE\r\n"
            "YJG+SwuBOgd+ei1ExwIDAQAB\r\n"
            "-----END PUBLIC KEY-----'"
            ")"
        ),
    ]
