# Generated by Django 4.0.2 on 2022-04-06 16:42

import django.db.models.deletion
from django.db import migrations, models

import gesasso.api.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asso",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=30)),
                ("shortname", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children",
                        to="proxy_pda.asso",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(gesasso.api.utils.GetFreshMixin, models.Model),
        ),
    ]
