version: "3.9"
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: gesasso
      MARIADB_DATABASE: gesasso
      MARIADB_USER: gesasso
      MARIADB_PASSWORD: gesasso
  web:
    build: ""
    environment:
      GESASSO_EMAIL_HOST: "mailserver"
      GESASSO_DJANGO_SECRET: "mysupersecretsecret"
      GESASSO_DJANGO_DEBUG: "True"
      GESASSO_DJANGO_ALLOWED_HOSTS: "*"
      GESASSO_DB_DEFAULT: "mysql://root:gesasso@db/gesasso"
      GESASSO_EMAIL_SUBJECT_PREFIX: "[gesasso] "
      GESASSO_OAUTH_SETTINGS_ID: "YOUR_ID"
      GESASSO_OAUTH_SETTINGS_SECRET: "YOUR_SECRET"
      GESASSO_LOGLEVEL: "INFO"
      GESASSO_SENTRY_DSN: "https://68b09d388764458fb1df100166f44b08@o1296214"
      GESASSO_DISABLE_SYNC_ASSOS: "True"
    ports:
      - "8003:8003"
    volumes:
      - .:/code
      - ./tmp/:/tmp/uploads/
    links:
      - db
    depends_on:
      - db
networks:
  default:
    name: external-example
