# Generated by Django 3.2.8 on 2021-10-29 14:53

from django.db import migrations, models
import django.db.models.deletion
import gesasso.api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(gesasso.api.utils.TimeStampableMixin, gesasso.api.utils.GetFreshMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Asso',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('target', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=(gesasso.api.utils.TimeStampableMixin, gesasso.api.utils.GetFreshMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasktype')),
            ],
            options={
                'abstract': False,
            },
            bases=(gesasso.api.utils.TimeStampableMixin, gesasso.api.utils.GetFreshMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('user', models.CharField(max_length=150)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OPEN'), (2, 'ASSIGNED'), (3, 'CLOSED'), (4, 'DONE'), (5, 'WAITING_TECH'), (6, 'WAITING_FOR_TIERS_SERVICE'), (7, 'WAITING_FOR_CUSTOMER')], default=1)),
                ('actions', models.ManyToManyField(to='api.Action')),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asso')),
            ],
            options={
                'abstract': False,
            },
            bases=(gesasso.api.utils.TimeStampableMixin, gesasso.api.utils.GetFreshMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('tasks_types', models.ManyToManyField(to='api.TaskType')),
            ],
            options={
                'abstract': False,
            },
            bases=(gesasso.api.utils.TimeStampableMixin, gesasso.api.utils.GetFreshMixin, models.Model),
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actiontype'),
        ),
    ]
