# Generated by Django 3.1.12 on 2021-10-25 08:03

from django.db import migrations, models
import django.db.models.deletion
import gesasso.api.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tasktype"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("tasks", models.ManyToManyField(to="api.TaskType")),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.actiontype"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
    ]
