# Generated by Django 3.2.8 on 2021-10-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "insert into `auth_user` values (NULL,'pbkdf2_sha256$260000$iIo10PRNOmFS2TV4IL1fQV$QO6IOwyYEZr6DAfMeY0NnPaPc+wSxmCJGCkuT1JqLNU=', '2021-10-27 07:54:39.676137', '1', 'gesasso', '', '', 'gesasso@assos.utc.fr', '1', '1', '2021-10-27 07:54:30.378407')"
        )
    ]
