# Generated by Django 4.0.2 on 2022-04-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_requestmessage_custom_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="custom_author_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
