# Generated by Django 3.2.8 on 2021-10-27 21:50

from django.db import migrations, models
import gesasso.api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_portailuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asso",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("removed", models.DateTimeField(blank=True, default=None, null=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=30)),
                ("shorname", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                gesasso.api.utils.TimeStampableMixin,
                gesasso.api.utils.GetFreshMixin,
                models.Model,
            ),
        ),
    ]
