# Generated by Django 3.2.8 on 2021-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_asso"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asso",
            old_name="shorname",
            new_name="shortname",
        ),
        migrations.RemoveField(
            model_name="asso",
            name="created",
        ),
        migrations.RemoveField(
            model_name="asso",
            name="removed",
        ),
        migrations.RemoveField(
            model_name="asso",
            name="updated",
        ),
        migrations.AddField(
            model_name="asso",
            name="name",
            field=models.CharField(default="coucou", max_length=150),
            preserve_default=False,
        ),
    ]
