# Generated by Django 3.2.8 on 2021-10-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211027_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='asso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asso'),
        ),
    ]
