on: push
name: BundleStat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Build
        with:
          cmd: build
      - name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: './gesasso/frontend/webpack-stats.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
