name: pre-commit

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - uses: pre-commit/action@v2.0.3
