name: Relative CI workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Disabled for now"
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16.x'
#          cache: 'yarn'
#
#      - name: Install dependencies 📦
#        run: yarn install --frozen-lockfile
#
#      - name: Build !📦
#        run: yarn build --json webpack-stats.json
#
#      # Send webpack stats and build information to RelativeCI
#      - name: Send webpack stats to RelativeCI
#        uses: relative-ci/agent-action@v2
#        with:
#          webpackStatsFile: ./webpack-stats.json
#          key: ${{ secrets.RELATIVE_CI_KEY }}
#          token: ${{ secrets.GITHUB_TOKEN }}
